services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    networks:
      - mynetwork

  backend:
    image: backend-image:latest
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/memories
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    depends_on:
      - mongo_db
      - redis
    deploy:
      replicas: 3
    networks:
      - mynetwork

  frontend:
    image: frontend-image:latest
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    deploy:
      replicas: 2
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
volumes:
  mongo_db: {}