services:
  backend1:
    image: backend1
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo

  backend2:
    image: backend2
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo

  backend3:
    image: backend3
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    depends_on:
      - mongo

  react-app:
    image: react-app
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend1
      - backend2
      - backend3

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - react-app
      - backend1
      - backend2
      - backend3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  mongo-data:
