services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    networks:
      - mynetwork

  backend:
    image: nodejs-backend
    build: ./backend
    networks:
      - mynetwork
    depends_on:
      - mongo_db
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      MONGO_URI: mongodb://mongo_db:27017/memories
      REDIS_HOST: redis
      REDIS_PORT: 6379

  # Frontend service
  frontend:
    image: react-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
    depends_on:
      - backend

networks:
  mynetwork:

volumes:
  mongo_db: {}
